service: birthday-checker

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

functions:
  checker:
    handler: handler.checker
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - schedule:
          rate: cron(15 10 * * ? *)
          enabled: true
